version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:14.7
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sonet_core
      PGDATA: /data/postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
#    volumes:
#      - ./postgres/:/data/postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    restart: unless-stopped
  sonet-core:
    image: 'sonet-core:latest'
    build:
      context: .
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/postgres